os: osx
language: python
python:
- "3.6"
before install:
- python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U flake8
install:
- pip install -r requirements.txt
script:
- pytest
- flake8
