name: ghf_build

on:
    push:
        branches:
            - develop
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6, 3.7]
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - uses: goanpeca/setup-miniconda@v1
            with:
              activate-environment: ghf
              environment-file: environment.yml
              python-version: ${{ matrix.python-version }}
        - name: Test with pytest
          run: | 
            conda env create -f environment.yml python=${{ matrix.python-version }}
            source activate ghf
            pip install pytest
            pip install ".[test]"
            pytest

